In [1]:
import create_r3d_functions as c3d

#c3d.create_grid(100,9,[100.0/2, 100.0/4, 100.0/8, 100.0/16])

c3d.create_grid(100,2,[100,50,25,12.5],'y')



Creating amr_grid with octree refinement.
Size of base cell: 100 AU
Number of base cells along one side of the grid: 2
Distances to refinement limits: [100, 50, 25, 12.5] AU
Number refinements: 4
Length of total side of whole grid: 200.00 AU

Child cell size 0: 50.0 AU
Child cell size 1: 25.0 AU
Child cell size 2: 12.5 AU
Child cell size 3: 6.25 AU

Writing amr_grid.inp
Finished amr_grid.inp

Writing grid_distances.dat (not necessary for Radmc3d, but useful for pre/portprocessing of your model files. It has the same order as dust_densities.inp)

Done


In [11]:
import numpy as np

test = np.zeros((10,4))

print(test)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
refdistance = np.sqrt(
(griddist[nx] + gridcorrx[0][child1] + gridcorrx[1][child2] + gridcorrx[2][child3])**2 + 
(griddist[ny] + gridcorry[0][child1] + gridcorry[1][child2] + gridcorry[2][child3])**2 + 
(griddist[nz] + gridcorrz[0][child1] + gridcorrz[1][child2] + gridcorrz[2][child3])**2
)

refinearray1[nn + counter[0]*8] = 1, 0, 2 (men inte mer)

refinearray2[nn + sum(counter)*8 + child1+1] = 2,0,3
# counter 0 och 1
refinearray3[nn + sum(counter)*8 + child1+child2+2] = 3,0,4
# counter 0 1 2





In [9]:
print(f'{1230000000000.0}')

1230000000000.0
