In [1]:
import create_r3d_functions as c3d
import plot_r3d_functions as p3d
#c3d.create_grid(100,9,[100.0/2, 100.0/4, 100.0/8, 100.0/16])

#c3d.create_grid(100,2,[100,50,25,12.5])

p3d.plot_grid()





<class 'int'>


In [6]:
string = '-1.111a'

string[-1].isdigit()

False

In [2]:
import numpy as np
print(np.zeros((10,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
